language: ruby
rvm: 2.5.1
services: postgresql
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- bundle exec rake db:create
- bundle exec rake db:migrate
script: bundle exec rspec spec/
notifications:
  slack:
    secure: n4pJvsppbSYSE5/EuWU0+SQ6rfPOc8Q25fgKbkwqytzUwrambTcx6j0IIAV3dPWfJ6cJ1alPROjBHemonnxUR/SABHeX6OKF7H3ILfS5Z48wqg3N4/R55PxsZ7NyTQGMyzSIJxkdEXva8LolveHcH2vf4xrfC+cx3nvBls089VEKFvC5uPyuPhp0r1kMYLXqqOa2urNrNEBn+YhIlkxdg7AUZkAAkFmU3Ozxp8zLkkoWdxhegPLq24jCLqKMvvkQE/Qp5sEsqCojmkbBWI39y1RnGDnXzzB27ASRQYaOEqmIJKKBNtfUcjkTTRnHqR7zg7/3c34AcpcP9mrv2yirad4aaZ03QYb0ltCvOgojAh1WmPr4BCvrtWCmNu+RlhoIFwDOoldzOMTegR4kY6sOaqxaOv2BvLi7RBmv6uN1S2kgkkKVT6XNsis/ssgFYcj7Uyp7lYp8SqUycS36qXACHeKwkkZ10+0Dm+zspihWAtb6ywTDqqrTOeg9jEVA3VCAvPHNiNGT2AV7tGcXRAzUyHdGLVpZe7eUoxQwI8Wz790+rnpoymJSD4SRUegcvbTxUQDmJtJcGhqg4bulIciggJHGZ00PzhIpuZqCYirAu/vpkLClF+Nj2ncF8H3G4Dssoj/klJjpK/EDUxYQ05TbLmotWjs+Dg8qQ7HHR/auUQY=
env:
  global:
    secure: oG65O4PDAnZ1sAPQOR11l0QUMu4Zt0UKGaOnRx2jhOpq76SxV1aQavYbcJHzjHIEiYca2vvxcZD1qGSVjr3FSdmhD0+q+TWk5NsbomIRv3/6Te37sKZ+MV5ox9tGAMJdQ52t7lsPG80WjsUPavr+8THDAfmYCmGYtZIhfz41wGN1ckD9Wju7o0V5K76QjkcMKTjt2PC8rBJ5KWexSLnCVvDQuHUobROcPb0onDGUK5aUE96hoAeRNNSBsHjWHeefTxQHw7MQreqiMkCjoKPnE0Xh8aealIDu9Rj5CsSgLqJmGtfqq3OuEDc+A7zp+rsiPB2QN2u4TQz7hIwbKwRPEcEzGXtY4LjSU/+iteIbUH9mnKB9L+uXahNIk1//tvqiVOZJ8Ua56KdOkEq91/hxd3cG33CLHzs+1NclhPRG2rKVdpbCjLO4J2CJ6/09tQCdrtOLGbfuLH/hIPk85MiEzm0Z9pe21dSdTkKbKxSWm4MVP3kyz05GgHJPx6TBNyQs4hE7QqRwFq4zSGoYssaUoB93eUGpkTYCIEX45uRi8peCG4jnToCcxLIMIkfjwRYOyYYJiUcTRgM40kp0kZ6JAlqcICDrYTlC/GVIy27uT9G/+cCamqXrN9UDyzJ1fJf0l+AVoIrrkBUJ8Y+MAJVmZWtvFwrJIdPjo39L2lMJ0w0=
deploy:
  provider: heroku
  api_key:
    secure: reIYGjQWQ1zHV4AgiFVsD5XNEW4roP87dJsvRPkpZPMSiyTBRhRmoxJBPTVerjRMN745u4Uw27V7IX4KW0NBnjWvmEF7+nbQRedSFEKIpKfyz94RR5bnTVRcPa20A6WaXL0HqZ/AUNeGR6YGgDob3EpGENh4NZ3pt5oKY00qER2eMAqLJOKXxJpuEv2KlxkShbefVoq3QWAHzftAalrTH7jxlO5Nxhth/7YjaeujHPdJ4frQ9Yk+e9osBxnLWiZqeN7SLs084tkHUVgys83mQ4YcrXU6QPWwH/kbLp7WGSer7nI2lgSHu03betHcegzS/S83qOvkZAgz/7/NEBNqr+X75oZou9dCLtNrWpAa5QmctyaQ/pcoyM7gSyV81Oj+2kmOs8W76+7WfFH7hBWCZ6jbo+VdZplrkxZzmPbUPH5oiuB8AUnrcMGn3II7L6LWdyxE6z6gNDJuO70DyzSSdm38ZSM1dzHDzox3nUHdmWWx7fzYis93bSABYeWd5vuJQyMx9nFDuwfMjULv2XXdLcFfXRJJmTnKrRx9btpbSgOGeOmOUjWjrYdp6CMXfLPTmwMvKHDV+smJCVsOMlJyxmy1C1RAi1SRvQBeMYm6psUB0y+zlmnJFPXhRPNV63Qo0jYuYHmnGfm/Y6OnCBDvuTeAr2H6ADhjG3Uh9cVTIXU=
  app: slack-slashcommand
  on:
    repo: keita-hino/slack-bot
    branch: master
    run: rake db:migrate
